[package]
name = "laststraw-core-macro"
version = "0.1.0"
edition = "2021"
authors = ["Hadrian Lazic"]

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
fs = "0.0.5"
laststraw-core = { path = "../core" }
quote = "1.0.38"
rusttype = "0.9.3"
syn = { version = "2.0.92", features = ["full"] }
