[package]
name = "laststraw-core-macro"
version = "0.1.0"                                                                    # Replace with the version you want to publish
edition = "2021"
authors = ["Hadrian Lazic"]
description = "Procedural macros for the lightweight GUI Rust framework Last-Straw."
license = "MIT OR Apache-2.0"
repository = "https://github.com/had2020/Last-Straw"
keywords = ["macro", "proc-macro", "rust", "gui"]
categories = ["gui", "rendering"]
homepage = "https://github.com/had2020/Last-Straw"

[lib]
path = "src/lib.rs"
proc-macro = true
