[package]
name = "laststraw-core-macro"
version = "0.1.0"
edition = "2021"
authors = ["Hadrian Lazic"]

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
glfw = "0.59.0"
laststraw-core= { path = "../core" }
quote = "1.0.38"
#syn = "2.0.92"
syn = { version = "2.0.92", features = ["full"] }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
