[package]
name = "laststraw-core"
version = "0.2.4"                                                               # Replace with the version you want to publish
edition = "2021"
authors = ["Hadrian Lazic"]
description = "Core library for the lightweight GUI Rust framework Last-Straw."
license = "MIT OR Apache-2.0"
repository = "https://github.com/had2020/Last-Straw"
keywords = ["framework", "rust", "gui"]
categories = ["gui", "rendering"]
homepage = "https://github.com/had2020/Last-Straw"

[lib]
path = "src/lib.rs"

[dependencies]
freetype-rs = "0.37.0"
minifb = "0.27.0"
rusttype = "0.9.3"
