[package]
name = "laststraw-core"
version = "0.0.1"
edition = "2021"
authors = ["Hadrian Lazic"]

[lib]
path = "src/lib.rs"
#proc-macro = true

[dependencies]
freetype-rs = "0.37.0"
gl = "0.14.0"
glfw = "0.59.0"
minifb = "0.27.0"
#laststraw-core-macro= { path = "../core-macro" } no longer needed


[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
